/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demonotepad;

import demonotepad.PageSetupDialog;
import java.awt.event.KeyEvent;
import java.io.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.net.URI;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.undo.UndoManager;

/**
 *
 * @author Phạm Văn Hiếu
 */
public class DemoNotePad extends javax.swing.JFrame {
    String fileName;
    String fileAdress;
//    DemoNotePad notepad;
    
    Function_File file= new Function_File(this);
    Function_Format format= new Function_Format(this);
    Function_Edit edit= new Function_Edit(this);
    Function_View view= new Function_View(this);
    /**
     * Creates new form DemoNotePad
     */
    public DemoNotePad() {
        
        setBounds(0, 0, 1950, 1050);
        initComponents();
//        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconImages/notepad.jpg"))); 
        
        JmenuFile.setMnemonic(KeyEvent.VK_F);
        //  
            iNew.getColorModel();
            iNew.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N,InputEvent.CTRL_DOWN_MASK));
            iNewWindow.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N,InputEvent.CTRL_DOWN_MASK | InputEvent.SHIFT_DOWN_MASK));
            
            iSave.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S,InputEvent.CTRL_DOWN_MASK));
            iSaveAs.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S,InputEvent.CTRL_DOWN_MASK | InputEvent.SHIFT_DOWN_MASK));
            
            iPrint.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_P,InputEvent.CTRL_DOWN_MASK));
            iExit.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_E,InputEvent.CTRL_DOWN_MASK));
        //
        JmenuEdit.setMnemonic(KeyEvent.VK_E);
        //
            itemUndo.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_Z,InputEvent.CTRL_DOWN_MASK));
            
            itemCut.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_X,InputEvent.CTRL_DOWN_MASK));
            
            itemCoopy.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C,InputEvent.CTRL_DOWN_MASK));
            
            itemPaste.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_V,InputEvent.CTRL_DOWN_MASK));
            
            itemDele.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE,0));
            
            itemSearch.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_E,InputEvent.CTRL_DOWN_MASK));
            
            itemFind.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F,InputEvent.CTRL_DOWN_MASK));
            
            itemFindN.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F3,0));
            
            itemFindP.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F3,InputEvent.SHIFT_DOWN_MASK));
            
            itemRP.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_H,InputEvent.CTRL_DOWN_MASK));
            
            itemGT.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_G,InputEvent.CTRL_DOWN_MASK));
            
            itemSA.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A,InputEvent.CTRL_DOWN_MASK));
            
            itemTimeDay.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F6,0));
        //
        JmenuFormat.setMnemonic(KeyEvent.VK_F);
        JmenuView.setMnemonic(KeyEvent.VK_V);
        JmenuHelp.setMnemonic(KeyEvent.VK_H);
        
    }

    public JTextArea getTxtANotepad() {
        return txtANotepad;
    }
    public JMenuItem getitemFindN() {
        return itemFindN;
    }
    public JMenuItem getitemFindP() {
        return itemFindP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtANotepad = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmenuFile = new javax.swing.JMenu();
        iNew = new javax.swing.JMenuItem();
        iNewWindow = new javax.swing.JMenuItem();
        iOpen = new javax.swing.JMenuItem();
        iSave = new javax.swing.JMenuItem();
        iSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        iPageSetup = new javax.swing.JMenuItem();
        iPrint = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        iExit = new javax.swing.JMenuItem();
        JmenuEdit = new javax.swing.JMenu();
        itemUndo = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemCut = new javax.swing.JMenuItem();
        itemCoopy = new javax.swing.JMenuItem();
        itemPaste = new javax.swing.JMenuItem();
        itemDele = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemSearch = new javax.swing.JMenuItem();
        itemFind = new javax.swing.JMenuItem();
        itemFindN = new javax.swing.JMenuItem();
        itemFindP = new javax.swing.JMenuItem();
        itemRP = new javax.swing.JMenuItem();
        itemGT = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        itemSA = new javax.swing.JMenuItem();
        itemTimeDay = new javax.swing.JMenuItem();
        JmenuFormat = new javax.swing.JMenu();
        chkWordWrap = new javax.swing.JCheckBoxMenuItem();
        iFont = new javax.swing.JMenuItem();
        JmenuView = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        iZoomIn = new javax.swing.JMenuItem();
        iZoomOut = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        JmenuHelp = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Untitled - Notepad");

        txtANotepad.setColumns(20);
        txtANotepad.setRows(5);
        jScrollPane1.setViewportView(txtANotepad);

        jCheckBox1.setText("jCheckBox1");

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        JmenuFile.setBackground(new java.awt.Color(255, 255, 255));
        JmenuFile.setText("File");

        iNew.setBackground(new java.awt.Color(255, 255, 255));
        iNew.setText("New");
        iNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNewActionPerformed(evt);
            }
        });
        JmenuFile.add(iNew);

        iNewWindow.setBackground(new java.awt.Color(255, 255, 255));
        iNewWindow.setText("New Window");
        iNewWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNewWindowActionPerformed(evt);
            }
        });
        JmenuFile.add(iNewWindow);

        iOpen.setBackground(new java.awt.Color(255, 255, 255));
        iOpen.setText("Open...");
        iOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iOpenActionPerformed(evt);
            }
        });
        JmenuFile.add(iOpen);

        iSave.setBackground(new java.awt.Color(255, 255, 255));
        iSave.setText("Save");
        iSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSaveActionPerformed(evt);
            }
        });
        JmenuFile.add(iSave);

        iSaveAs.setBackground(new java.awt.Color(255, 255, 255));
        iSaveAs.setText("Save As...");
        iSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSaveAsActionPerformed(evt);
            }
        });
        JmenuFile.add(iSaveAs);
        JmenuFile.add(jSeparator1);

        iPageSetup.setBackground(new java.awt.Color(255, 255, 255));
        iPageSetup.setText("Page Setup...");
        iPageSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iPageSetupActionPerformed(evt);
            }
        });
        JmenuFile.add(iPageSetup);

        iPrint.setBackground(new java.awt.Color(255, 255, 255));
        iPrint.setText("Print");
        iPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iPrintActionPerformed(evt);
            }
        });
        JmenuFile.add(iPrint);
        JmenuFile.add(jSeparator2);

        iExit.setBackground(new java.awt.Color(255, 255, 255));
        iExit.setText("Exit");
        iExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iExitActionPerformed(evt);
            }
        });
        JmenuFile.add(iExit);

        jMenuBar1.add(JmenuFile);

        JmenuEdit.setBackground(new java.awt.Color(255, 255, 255));
        JmenuEdit.setText("Edit");

        itemUndo.setText("Undo");
        itemUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUndoActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemUndo);
        JmenuEdit.add(jSeparator3);

        itemCut.setText("Cut");
        itemCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCutActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemCut);

        itemCoopy.setText("Coppy");
        itemCoopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCoopyActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemCoopy);

        itemPaste.setText("Paste");
        itemPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPasteActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemPaste);

        itemDele.setText("Delete");
        itemDele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeleActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemDele);
        JmenuEdit.add(jSeparator4);

        itemSearch.setText("Search with Bring...");
        itemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSearchActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemSearch);

        itemFind.setText("Find...");
        itemFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFindActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemFind);

        itemFindN.setText("Find Next");
        itemFindN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFindNActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemFindN);

        itemFindP.setText("Find Previuos");
        itemFindP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFindPActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemFindP);

        itemRP.setText("Replace...");
        itemRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRPActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemRP);

        itemGT.setText("Go To...");
        itemGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGTActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemGT);
        JmenuEdit.add(jSeparator5);

        itemSA.setText("Select All");
        itemSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSAActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemSA);

        itemTimeDay.setText("Time/Date");
        itemTimeDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTimeDayActionPerformed(evt);
            }
        });
        JmenuEdit.add(itemTimeDay);

        jMenuBar1.add(JmenuEdit);

        JmenuFormat.setBackground(new java.awt.Color(255, 255, 255));
        JmenuFormat.setText("Format");

        chkWordWrap.setSelected(true);
        chkWordWrap.setText("Word Wrap");
        JmenuFormat.add(chkWordWrap);

        iFont.setText("Font...");
        iFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iFontActionPerformed(evt);
            }
        });
        JmenuFormat.add(iFont);

        jMenuBar1.add(JmenuFormat);

        JmenuView.setBackground(new java.awt.Color(255, 255, 255));
        JmenuView.setText("View");

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setText("Zoom");

        iZoomIn.setText("Zoom In");
        iZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iZoomInActionPerformed(evt);
            }
        });
        jMenu6.add(iZoomIn);

        iZoomOut.setText("Zoom Out");
        iZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iZoomOutActionPerformed(evt);
            }
        });
        jMenu6.add(iZoomOut);

        jMenuItem13.setText("Restore Default Zoom");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        JmenuView.add(jMenu6);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Status Bar");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        JmenuView.add(jCheckBoxMenuItem1);

        jMenuBar1.add(JmenuView);

        JmenuHelp.setBackground(new java.awt.Color(255, 255, 255));
        JmenuHelp.setText("Help");

        jMenuItem14.setText("View Help");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        JmenuHelp.add(jMenuItem14);

        jMenuItem15.setText("Send Feedback");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        JmenuHelp.add(jMenuItem15);
        JmenuHelp.add(jSeparator6);

        jMenuItem16.setText("About Notepad");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        JmenuHelp.add(jMenuItem16);

        jMenuBar1.add(JmenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNewActionPerformed
        // TODO add your handling code here:
        file.newFile();
    }//GEN-LAST:event_iNewActionPerformed

    private void iNewWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNewWindowActionPerformed
        // TODO add your handling code here:
//        DemoNotePad notepad= new DemoNotePad();
//        notepad.setLocationRelativeTo(this);
//        notepad.setVisible(true);
            if(evt.getSource()==iNewWindow){
                DemoNotePad notepad= new DemoNotePad();
                notepad.setLocationRelativeTo(this);
                notepad.setVisible(true);
            }
            
    }//GEN-LAST:event_iNewWindowActionPerformed

    private void iOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iOpenActionPerformed
        // TODO add your handling code here:
        file.openFile();
    }//GEN-LAST:event_iOpenActionPerformed

    private void iSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSaveActionPerformed
        // TODO add your handling code here:
        file.saveFile();
    }//GEN-LAST:event_iSaveActionPerformed

    private void iSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSaveAsActionPerformed
        // TODO add your handling code here:
        file.saveAsFile();
    }//GEN-LAST:event_iSaveAsActionPerformed

    private void iPageSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iPageSetupActionPerformed
        if(evt.getSource()==iPageSetup){
                PageSetupDialog pagesetup= new PageSetupDialog(this,false);
                pagesetup.setLocationRelativeTo(this);
                pagesetup.setVisible(true);
                
            }
    }//GEN-LAST:event_iPageSetupActionPerformed

    private void iPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iPrintActionPerformed

    private void iExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iExitActionPerformed
        // TODO add your handling code here:
        file.exit();
    }//GEN-LAST:event_iExitActionPerformed

    private void itemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemUndoActionPerformed

    private void itemCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCutActionPerformed
        // TODO add your handling code here:
        edit.cutFile();
    }//GEN-LAST:event_itemCutActionPerformed

    private void itemCoopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCoopyActionPerformed
        // TODO add your handling code here:
        edit.coppyFile();
    }//GEN-LAST:event_itemCoopyActionPerformed

    private void itemPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPasteActionPerformed
        // TODO add your handling code here:
        edit.pastFile();
    }//GEN-LAST:event_itemPasteActionPerformed

    private void itemDeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeleActionPerformed
        // TODO add your handling code here:
        edit.deleteFile();
    }//GEN-LAST:event_itemDeleActionPerformed

    private void itemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSearchActionPerformed
        // TODO add your handling code here:
        try {
            Desktop des=Desktop.getDesktop();
            String text= txtANotepad.getSelectedText().replace(" ", "+");
            des.browse(new URI("http://www.bing.com/search?q=" + text + "&form=NPCTXT"));
        } catch (Exception e) {
            System.err.println(e.toString());
        }
        
    }//GEN-LAST:event_itemSearchActionPerformed

    private void itemFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFindActionPerformed
        // TODO add your handling code here:
        FindDialog find= new FindDialog(this, false);
        find.setLocationRelativeTo(this);
        find.setVisible(true);
        
    }//GEN-LAST:event_itemFindActionPerformed

    private void itemFindNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFindNActionPerformed
        // TODO add your handling code here:
        FindDialog find= new FindDialog(this, false);
        find.setLocationRelativeTo(this);
    }//GEN-LAST:event_itemFindNActionPerformed

    private void itemFindPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFindPActionPerformed
        // TODO add your handling code here:
        FindDialog find= new FindDialog(this, false);
        find.setLocationRelativeTo(this);
        edit.FindP();
    }//GEN-LAST:event_itemFindPActionPerformed

    private void itemRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRPActionPerformed

    private void itemGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGTActionPerformed

    private void itemSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSAActionPerformed
        // TODO add your handling code here:
        edit.selectAllFile();
    }//GEN-LAST:event_itemSAActionPerformed

    private void itemTimeDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTimeDayActionPerformed
        edit.timeDateFile();
    }//GEN-LAST:event_itemTimeDayActionPerformed

    private void iFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iFontActionPerformed
        // TODO add your handling code here:
        FontDialog font= new FontDialog(this, true);
        font.setLocationRelativeTo(this);
        font.setVisible(true);
    }//GEN-LAST:event_iFontActionPerformed

    private void iZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iZoomInActionPerformed
        // TODO add your handling code here:
        view.zoomInFile();
    }//GEN-LAST:event_iZoomInActionPerformed

    private void iZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iZoomOutActionPerformed
        // TODO add your handling code here:
        view.zoomOutFile();
    }//GEN-LAST:event_iZoomOutActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop des= Desktop.getDesktop();
            des.browse(new URI("https://www.bing.com/search?q=get+help+with+notepad+in+windows+10&filters=guid:%224466414-en-dia%22%20lang:%22en%22&form=T00032&ocid=HelpPane-BingIA"));
        }catch(Exception e){
            System.err.println(e.toString());
        }
        
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
//        AboutDialog about= new AboutDialog(this, true);
//        about.setLocationRelativeTo(this);
//        about.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoNotePad().setVisible(true);
                
            }
        });
    }
    
//    @Override
//    public void actionPerformed(ActionEvent e) {
//        String command= e.getActionCommand();
//        switch(command){
//            case "New": file.newFile(); break;
//            case "Open": file.openFile(); break;
//            case "Save": file.saveFile(); break;
//            case "Save As": file.saveAsFile(); break;
//            
//            
//            case "Undo": edit.undoFile();break;
//            case "Cut": edit.cutFile();break;
//            case "Coppy": edit.coppyFile();break;
//            case "Past": edit.pastFile();break;
//            case "Delete": edit.deleteFile();break;
//            
//            
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JmenuEdit;
    private javax.swing.JMenu JmenuFile;
    private javax.swing.JMenu JmenuFormat;
    private javax.swing.JMenu JmenuHelp;
    private javax.swing.JMenu JmenuView;
    private javax.swing.JCheckBoxMenuItem chkWordWrap;
    private javax.swing.JMenuItem iExit;
    private javax.swing.JMenuItem iFont;
    private javax.swing.JMenuItem iNew;
    private javax.swing.JMenuItem iNewWindow;
    private javax.swing.JMenuItem iOpen;
    private javax.swing.JMenuItem iPageSetup;
    private javax.swing.JMenuItem iPrint;
    private javax.swing.JMenuItem iSave;
    private javax.swing.JMenuItem iSaveAs;
    private javax.swing.JMenuItem iZoomIn;
    private javax.swing.JMenuItem iZoomOut;
    private javax.swing.JMenuItem itemCoopy;
    private javax.swing.JMenuItem itemCut;
    private javax.swing.JMenuItem itemDele;
    private javax.swing.JMenuItem itemFind;
    private javax.swing.JMenuItem itemFindN;
    private javax.swing.JMenuItem itemFindP;
    private javax.swing.JMenuItem itemGT;
    private javax.swing.JMenuItem itemPaste;
    private javax.swing.JMenuItem itemRP;
    private javax.swing.JMenuItem itemSA;
    private javax.swing.JMenuItem itemSearch;
    private javax.swing.JMenuItem itemTimeDay;
    private javax.swing.JMenuItem itemUndo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JTextArea txtANotepad;
    // End of variables declaration//GEN-END:variables
}
